name: Drivers test run

on: push

jobs:
  js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
      - run: apt-get update && apt-get install -y software-properties-common npm
      - run: npm install -g npm@latest; npm install -g bun deno-bin
      - run: cd drivers/js/nodejs && zig build && cd ..
      - run: npm run nodejs-test
      - run: npm run bun-test
      - run: npm run deno-test